// pen-audit の配布バンドルを作る。
//
// JavaScript アクションはリポジトリに置かれたファイルをそのまま実行するので、
// 依存 (zod) ごと 1 ファイルに固めて dist/ にコミットしている。
// ソースを触ったら `npm run build:action` を実行すること。CI が差分を検出して落とす。

import { build } from 'esbuild';

const result = await build({
  entryPoints: ['tools/pen-audit/src/index.ts'],
  outfile: 'tools/pen-audit/dist/pen-audit.mjs',
  bundle: true,
  minify: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  legalComments: 'none',
  banner: {
    js: '// Generated by `npm run build:action`. Do not edit. Source: tools/pen-audit/src/',
  },
  metafile: true,
});

const [outputPath, output] = Object.entries(result.metafile.outputs)[0];
console.log(`${outputPath}  ${(output.bytes / 1024).toFixed(1)} KB`);
